(()=>{
"use strict";
const DEFAULT_CONFIG={manifestUrl:null,targetUrl:"../w3.zip",cacheName:"file-merge-cache",partBase:"../part/w3.zip.part",partStart:1,partEnd:99,parts:null};
const userConfig=typeof window!=="undefined"&&window.FILE_MERGE_CONFIG?window.FILE_MERGE_CONFIG:{};
let config=Object.assign({},DEFAULT_CONFIG,userConfig),mergePromise=null,resolvedParts=null,resolvedTarget=null,resolvedAbsoluteTarget=null;
const progressState={phase:"idle",partIndex:0,partCount:0,partName:"",partLoaded:0,partTotal:0,totalLoaded:0,totalExpected:0,mergeOffset:0,mergeTotal:0};
let uiRoot=null,uiLog=null,uiCursor=null,lastUiLog="",uiStyle=null,lineCount=0;
function bringToFront(){if(!uiRoot)return;const p=document.documentElement||document.body;if(!p)return;if(uiRoot.parentNode!==p||p.lastChild!==uiRoot)p.appendChild(uiRoot);uiRoot.style.zIndex="2147483647";uiRoot.style.display="flex";uiRoot.style.visibility="visible";uiRoot.style.opacity="1";uiRoot.style.pointerEvents="auto"}
function ensureUI(){const host=document.body||document.documentElement;if(!host){document.addEventListener("DOMContentLoaded",ensureUI,{once:true});return}
if(!uiStyle){uiStyle=document.createElement("style");uiStyle.id="filemerge-style";uiStyle.textContent="#filemerge-overlay{position:fixed!important;inset:0!important;z-index:2147483647!important;display:flex!important;align-items:center;justify-content:center;background:#0a0a0a!important;color:#33ff66!important;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace!important;margin:0!important;padding:20px!important;box-sizing:border-box!important}#filemerge-overlay.filemerge-hide{opacity:0!important;pointer-events:none!important;transition:opacity .35s ease}#filemerge-term{width:min(96vw,720px);max-height:86vh;display:flex;flex-direction:column;background:#0c0c0c;border:1px solid #1f3d1f;border-radius:8px;box-shadow:0 0 0 1px #0a1a0a,0 20px 60px rgba(0,0,0,.7);overflow:hidden}#filemerge-term-bar{display:flex;align-items:center;gap:8px;padding:10px 12px;background:#111;border-bottom:1px solid #1a1a1a;color:#8a8a8a;font-size:12px;user-select:none}#filemerge-term-bar .dots{display:flex;gap:6px}#filemerge-term-bar .dot{width:10px;height:10px;border-radius:50%}#filemerge-term-bar .dot.r{background:#ff5f56}#filemerge-term-bar .dot.y{background:#ffbd2e}#filemerge-term-bar .dot.g{background:#27c93f}#filemerge-term-bar .title{flex:1;text-align:center;color:#6f6;letter-spacing:.04em}#filemerge-log{flex:1;min-height:280px;max-height:70vh;overflow:auto;padding:14px 16px 8px;font-size:13px;line-height:1.55;color:#33ff66;white-space:pre-wrap;word-break:break-all;background:#0c0c0c}#filemerge-log .line{margin:0 0 2px}#filemerge-log .line.err{color:#ff6b6b}#filemerge-log .line.info{color:#7dd3fc}#filemerge-log .line.ok{color:#86efac}#filemerge-prompt{padding:0 16px 14px;color:#33ff66;font-size:13px}#filemerge-cursor{display:inline-block;width:8px;height:14px;background:#33ff66;margin-left:4px;vertical-align:-2px;animation:filemerge-blink 1s step-end infinite}@keyframes filemerge-blink{50%{opacity:0}}";(document.head||document.documentElement).appendChild(uiStyle)}
if(!uiRoot||!document.getElementById("filemerge-overlay")){uiRoot=document.createElement("div");uiRoot.id="filemerge-overlay";uiRoot.innerHTML='<div id="filemerge-term"><div id="filemerge-term-bar"><div class="dots"><span class="dot r"></span><span class="dot y"></span><span class="dot g"></span></div><div class="title">file-merge</div></div><div id="filemerge-log"></div><div id="filemerge-prompt">$ <span id="filemerge-cursor"></span></div></div>';host.appendChild(uiRoot);lineCount=0;lastUiLog=""}else uiRoot=document.getElementById("filemerge-overlay");
uiLog=document.getElementById("filemerge-log");uiCursor=document.getElementById("filemerge-cursor");bringToFront()}
function appendLog(line,kind){ensureUI();bringToFront();if(!uiLog){console.log("[FileMerge]",line);return}if(line===lastUiLog)return;lastUiLog=line;const time=new Date().toLocaleTimeString(),row=document.createElement("div");row.className="line"+(kind?" "+kind:"");row.textContent="["+time+"] "+line;uiLog.appendChild(row);lineCount++;while(lineCount>400&&uiLog.firstChild){uiLog.removeChild(uiLog.firstChild);lineCount--}uiLog.scrollTop=uiLog.scrollHeight}
function hideUISoon(){if(!uiRoot)return;setTimeout(function(){if(!uiRoot)return;uiRoot.classList.add("filemerge-hide");setTimeout(function(){if(uiRoot&&uiRoot.parentNode)uiRoot.parentNode.removeChild(uiRoot);uiRoot=null;uiLog=null;uiCursor=null},400)},900)}
function formatBytes(n){if(!n||n<0)return"0 B";const u=["B","KB","MB","GB"];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return v.toFixed(i===0?0:2)+" "+u[i]}
function emitProgress(extra){const s=Object.assign({},progressState,extra||{});Object.assign(progressState,s);const detail={phase:s.phase,partIndex:s.partIndex,partCount:s.partCount,partName:s.partName,partLoaded:s.partLoaded,partTotal:s.partTotal,totalLoaded:s.totalLoaded,totalExpected:s.totalExpected,mergeOffset:s.mergeOffset,mergeTotal:s.mergeTotal,partLoadedText:formatBytes(s.partLoaded),partTotalText:formatBytes(s.partTotal),totalLoadedText:formatBytes(s.totalLoaded),totalExpectedText:formatBytes(s.totalExpected),mergeOffsetText:formatBytes(s.mergeOffset),mergeTotalText:formatBytes(s.mergeTotal)};ensureUI();bringToFront();let logLine="",kind="";if(s.phase==="download")logLine="recv "+(s.partIndex+1)+"/"+s.partCount+"  "+s.partName+"  "+detail.partLoadedText+(s.partTotal?" / "+detail.partTotalText:"")+"  total "+detail.totalLoadedText+(s.totalExpected?" / "+detail.totalExpectedText:"");else if(s.phase==="merge")logLine="merge  "+detail.mergeOffsetText+" / "+detail.mergeTotalText;else if(s.phase==="done"){logLine="done   "+detail.totalLoadedText;kind="ok"}if(logLine){appendLog(logLine,kind);console.log("[FileMerge] "+logLine)}if(typeof config.onProgress==="function")try{config.onProgress(detail)}catch(_){}try{window.dispatchEvent(new CustomEvent("filemerge-progress",{detail:detail}))}catch(_){}}
function toAbsoluteUrl(url){try{return new URL(url,location.href).href}catch(_){return url}}
function normalizePartEntry(entry){if(typeof entry==="string")return{url:entry,name:entry};if(entry&&typeof entry==="object"&&entry.url)return{url:entry.url,name:entry.name||entry.url};throw new Error("无效的分片配置: "+JSON.stringify(entry))}
function generatePartsFromRange(){const start=Number(config.partStart),end=Number(config.partEnd),base=config.partBase||"../part/w3.zip.part";if(!Number.isFinite(start)||!Number.isFinite(end)||start>end)throw new Error("无效的分片范围: partStart="+config.partStart+", partEnd="+config.partEnd);const list=[];for(let i=start;i<=end;i++){const url=base+i;list.push({url:url,name:url})}return list}
function isTargetRequest(input){const targetAbs=resolvedAbsoluteTarget||toAbsoluteUrl(config.targetUrl);let reqUrl="";if(typeof input==="string")reqUrl=toAbsoluteUrl(input);else if(input&&typeof input.url==="string")reqUrl=toAbsoluteUrl(input.url);else return false;const a=reqUrl.split("#")[0].split("?")[0],b=targetAbs.split("#")[0].split("?")[0];if(a===b)return true;const name=(config.targetUrl||"").split("/").pop();return!!(name&&a.endsWith("/"+name))}
async function loadManifest(){if(Array.isArray(config.parts)&&config.parts.length>0){resolvedParts=config.parts.map(normalizePartEntry);resolvedTarget=config.targetUrl;resolvedAbsoluteTarget=toAbsoluteUrl(resolvedTarget);return}if(config.partStart!=null&&config.partEnd!=null&&config.partBase){resolvedParts=generatePartsFromRange();resolvedTarget=config.targetUrl;resolvedAbsoluteTarget=toAbsoluteUrl(resolvedTarget);appendLog("parts generated  "+config.partStart+".."+config.partEnd+"  count="+resolvedParts.length,"info");return}if(!config.manifestUrl)throw new Error("未配置 parts，也未配置 partStart/partEnd，也未配置 manifestUrl");appendLog("read manifest  "+config.manifestUrl,"info");const res=await window.__fileMergeNativeFetch(config.manifestUrl,{cache:"no-store"});if(!res.ok)throw new Error("清单加载失败: "+config.manifestUrl+" status="+res.status);const json=await res.json();if(!json||!Array.isArray(json.parts)||json.parts.length===0)throw new Error("清单中缺少有效的 parts 数组");resolvedParts=json.parts.map(normalizePartEntry);resolvedTarget=json.target||json.targetUrl||config.targetUrl;resolvedAbsoluteTarget=toAbsoluteUrl(resolvedTarget);if(!resolvedTarget)throw new Error("清单中缺少 target / targetUrl");appendLog("manifest ok  parts="+resolvedParts.length+"  target="+resolvedTarget,"info")}
async function fetchPartWithProgress(part,partIndex,partCount,baseLoaded){const res=await window.__fileMergeNativeFetch(part.url,{cache:"no-store"});if(!res.ok)throw new Error("分片加载失败: "+part.name+" status="+res.status);const totalHeader=Number(res.headers.get("content-length"))||0;if(!res.body||!res.body.getReader){const buf=await res.arrayBuffer();emitProgress({phase:"download",partIndex:partIndex,partCount:partCount,partName:part.name,partLoaded:buf.byteLength,partTotal:buf.byteLength,totalLoaded:baseLoaded+buf.byteLength,totalExpected:progressState.totalExpected||baseLoaded+buf.byteLength});return buf}const reader=res.body.getReader(),chunks=[];let loaded=0,lastEmit=0;for(;;){const result=await reader.read();if(result.done)break;chunks.push(result.value);loaded+=result.value.byteLength;const now=Date.now();if(now-lastEmit>=100||(totalHeader&&loaded>=totalHeader)){lastEmit=now;emitProgress({phase:"download",partIndex:partIndex,partCount:partCount,partName:part.name,partLoaded:loaded,partTotal:totalHeader,totalLoaded:baseLoaded+loaded,totalExpected:progressState.totalExpected})}}const out=new Uint8Array(loaded);let offset=0;for(let i=0;i<chunks.length;i++){out.set(chunks[i],offset);offset+=chunks[i].byteLength}emitProgress({phase:"download",partIndex:partIndex,partCount:partCount,partName:part.name,partLoaded:loaded,partTotal:totalHeader||loaded,totalLoaded:baseLoaded+loaded,totalExpected:progressState.totalExpected});return out.buffer}
async function mergeFiles(){if(mergePromise)return mergePromise;mergePromise=(async()=>{ensureUI();bringToFront();appendLog("file-merge start","info");await loadManifest();const targetUrl=resolvedTarget,parts=resolvedParts,cacheName=config.cacheName||"file-merge-cache";appendLog("target  "+targetUrl,"info");appendLog("parts   "+parts.length,"info");const cache=await caches.open(cacheName);let cached=(await cache.match(targetUrl))||(await cache.match(resolvedAbsoluteTarget));if(cached){appendLog("cache hit — skip download","ok");const len=Number(cached.headers.get("content-length"))||0;emitProgress({phase:"done",partIndex:parts.length-1,partCount:parts.length,partName:"cache",partLoaded:len,partTotal:len,totalLoaded:len,totalExpected:len,mergeOffset:len,mergeTotal:len});hideUISoon();return cached}appendLog("download begin","info");emitProgress({phase:"download",partIndex:0,partCount:parts.length,partName:parts[0].name,partLoaded:0,partTotal:0,totalLoaded:0,totalExpected:0,mergeOffset:0,mergeTotal:0});const buffers=[];let totalLoaded=0;for(let i=0;i<parts.length;i++){const buf=await fetchPartWithProgress(parts[i],i,parts.length,totalLoaded);buffers.push(buf);totalLoaded+=buf.byteLength;emitProgress({phase:"download",partIndex:i,partCount:parts.length,partName:parts[i].name,partLoaded:buf.byteLength,partTotal:buf.byteLength,totalLoaded:totalLoaded,totalExpected:progressState.totalExpected>totalLoaded?progressState.totalExpected:totalLoaded})}let totalSize=0;for(let i=0;i<buffers.length;i++)totalSize+=buffers[i].byteLength;appendLog("merge begin  "+formatBytes(totalSize),"info");emitProgress({phase:"merge",partIndex:parts.length-1,partCount:parts.length,partName:"merge",partLoaded:totalSize,partTotal:totalSize,totalLoaded:totalSize,totalExpected:totalSize,mergeOffset:0,mergeTotal:totalSize});const mergedArray=new Uint8Array(totalSize);let offset=0,lastEmit=0;for(let i=0;i<buffers.length;i++){mergedArray.set(new Uint8Array(buffers[i]),offset);offset+=buffers[i].byteLength;const now=Date.now();if(now-lastEmit>=50||offset===totalSize){lastEmit=now;emitProgress({phase:"merge",mergeOffset:offset,mergeTotal:totalSize,totalLoaded:totalSize,totalExpected:totalSize})}}appendLog("merge complete  "+totalSize+" bytes","ok");const finalResponse=new Response(mergedArray,{status:200,statusText:"OK",headers:{"Content-Type":"application/octet-stream","Content-Length":String(mergedArray.byteLength)}});await cache.put(targetUrl,finalResponse.clone());await cache.put(resolvedAbsoluteTarget,finalResponse.clone());appendLog("cache put ok","ok");emitProgress({phase:"done",mergeOffset:totalSize,mergeTotal:totalSize,totalLoaded:totalSize,totalExpected:totalSize});hideUISoon();return finalResponse})();try{return await mergePromise}catch(error){mergePromise=null;ensureUI();bringToFront();appendLog("error  "+(error&&error.message?error.message:error),"err");throw error}}
const nativeFetch=window.fetch.bind(window);window.__fileMergeNativeFetch=nativeFetch;
window.fetch=async function(input,init){if(isTargetRequest(input)){appendLog("intercept fetch → merged file","info");const res=await mergeFiles();return res.clone()}return nativeFetch(input,init)};
window.FileMergeLoader={load:mergeFiles,getConfig:function(){return Object.assign({},config)},setConfig:function(next){config=Object.assign({},config,next);mergePromise=null;resolvedParts=null;resolvedTarget=null;resolvedAbsoluteTarget=null},getProgress:function(){return Object.assign({},progressState)},get target(){return resolvedTarget||config.targetUrl},get parts(){if(resolvedParts)return resolvedParts.map(function(p){return p.url});if(config.partStart!=null&&config.partEnd!=null&&config.partBase)return generatePartsFromRange().map(function(p){return p.url});return(config.parts||[]).map(function(p){return typeof p==="string"?p:p.url})}};
const keepTopTimer=setInterval(function(){if(!uiRoot||!document.getElementById("filemerge-overlay"))return;if(progressState.phase==="done"){clearInterval(keepTopTimer);return}bringToFront()},300);
if(document.body||document.documentElement)ensureUI();else document.addEventListener("DOMContentLoaded",ensureUI,{once:true});
mergeFiles().catch(function(error){console.error("[FileMerge] 合并失败:",error)});
console.log("[FileMerge] 分片加载器已安装")
})();